# File:        DRESS/.travis.yml
# Authors:     Kevin Rak
# Description: This file defines the instructions for Travis CI
#              This file can be analyzed online at https://config.travis-ci.com/explore

language: cpp
os: linux
before_install:
  - curl -sS https://downloads.mariadb.com/MariaDB/mariadb_repo_setup | sudo bash
  - sudo apt-get remove --purge mysql-server mysql-client libmysqlclient-dev
install:
  - sudo apt-get update
  - sudo apt-get -y install mariadb-server libmariadb-dev libmariadbclient-dev libssl-dev
script:
  - mkdir build
  - cd build
  - cmake .. -DBUILD_CIVETWEB=ON -DBUILD_MARIADBCPP=ON
  - cmake --build . --target all --parallel $[`nproc`+1]
  - cmake ..
  - cmake --build . --target all --parallel $[`nproc`+1]
before_deploy:
  - cd $TRAVIS_BUILD_DIR
  - wget https://downloads.sourceforge.net/project/plantuml/plantuml.jar
  - sudo apt-get -y install doxygen graphviz
  - doxygen ../Doxyfile
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  local_dir: $TRAVIS_BUILD_DIR/docs/html
  token: $GH_REPO_TOKEN
  on:
    branch: master
