REATE USER 'monitor'@'%' IDENTIFIED BY 'monitor';
CREATE DATABASE DRESS_ATMOSPHERIC;
GRANT ALL PRIVILEGES ON DRESS_ATMOSPHERIC.* TO 'monitor'@'%';
use DRESS_ATMOSPHERIC;
CREATE TABLE DHT11(datetime DATETIME NOT NULL DEFAULT NOW(), sensor_number TEXT, temperature NUMERIC, humidity NUMERIC);
